In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
from sklearn.cluster import KMeans

In [64]:
df=pd.read_csv('Droom cluster data.xlsx - Sheet2.csv')

In [65]:
df.head(2)

ID     Make Model        Variant       Type Fuel Type Transmission  \
0   1  Hyundai   I10     Sportz 1.2  Hatchback    Petrol       Manual   
1   2  Hyundai   I20  Magna (O) 1.2  Hatchback    Petrol       Manual   

   on road price  
0         537850  
1         613863

In [4]:
df.dtypes

ID                int64
Make             object
Model            object
Variant          object
Type             object
Fuel Type        object
Transmission     object
on road price     int64
dtype: object

In [5]:
df.shape

(563, 8)

In [27]:
df['Kms_run'][1]

'31,143'

In [28]:
df['Kms_run']=df['Kms_run'].replace(",","",regex=True)

df['Ex_Showroom']=df['Ex_Showroom'].replace(" ","",regex=True)

In [29]:
df['Kms_run']=df['Kms_run'].astype(int)

In [30]:
df['Kms_run'].dtype

dtype('int64')

df['Insurance']=df['Insurance'].replace(",","",regex=True)

df['Insurance']=df['Insurance'].replace(" ","",regex=True)

df['Insurance']=df['Insurance'].astype(int)

df['Insurance'].dtype

In [6]:
df['Type'].unique()

array(['Hatchback', 'Sedan', 'SUV', 'MUV', 'Van', 'Crossover'],
      dtype=object)

In [7]:
df['Type'] = df['Type'].map( {'Hatchback': 1,'Crossover' : 0, 'Sedan':2,'SUV':3, 'MUV':4, 'Van':5 } ).astype(int)

In [8]:
df['Type'].dtype

dtype('int64')

In [9]:
df['Fuel Type'].unique()

array(['Petrol', 'Diesel', 'cng', 'diesel', 'CNG', 'LPG'], dtype=object)

In [11]:
df["Fuel Type"] = df["Fuel Type"].replace( ['Petrol','Petrol + CNG','Petrol + LPG' ], 'Petrol')
df["Fuel Type"] = df["Fuel Type"].replace(['Diesel','diesel'],'Diesel' )  
df["Fuel Type"] = df["Fuel Type"].replace(['CNG','cng' ], 'CNG')  
df["Fuel Type"] = df["Fuel Type"].replace(['LPG' ], 'LPG') 

In [12]:
df['Fuel Type'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG'], dtype=object)

In [13]:
df['Fuel Type'] = df['Fuel Type'].map( {'Petrol': 1,'Diesel' : 0, 'CNG':2, 'LPG':3} ).astype(int)

In [15]:
df['Fuel Type'].dtype

dtype('int64')

In [16]:
df['Make'].unique()

array(['Hyundai', 'Honda', 'Maruti Suzuki', 'Toyota'], dtype=object)

In [17]:
df['Make'] = df['Make'].map( {'Hyundai': 1,'Honda' : 0, 'Maruti Suzuki':2,'Toyota':3 } ).astype(int)

In [18]:
df['Make'].dtype

dtype('int64')

In [19]:
df.shape

(563, 8)

In [20]:
len(df['Variant'].unique())

474

In [22]:
M=df['Variant'].unique()
N=df['Variant']

In [23]:
n=0
for i in range(474):
    for j in range(563):
        if(M[i]==N[j]):
            N[j]=n
            
    n=n+1

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [24]:
df['Variant']=df['Variant'].astype(int)

In [25]:
df['Variant'].dtype

dtype('int64')

In [26]:
len(df['Model'].unique())

66

In [27]:
O=df['Model'].unique()
P=df['Model']

In [28]:
m=0
for i in range(66):
    for j in range(563):
        if(O[i]==P[j]):
            P[j]=m
            
    m=m+1

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [29]:
df['Model']=df['Model'].astype(int)

In [30]:
df['Model'].dtype

dtype('int64')

In [42]:
df['Model'].unique()

array(['I20', 'Neo Fluidic Elantra', 'Santro Xing', 'Grand I10', 'Accent',
       'Creta', 'Elite I20', 'Verna', 'I10', 'Eon', 'Xcent', 'Getz',
       'City', 'Accord', 'Ciaz', 'Wagon R', 'Swift', 'Innova', 'Fortuner',
       'Alto', 'Wagon R 1.0', 'Vitara Brezza', 'Amaze', 'Civic', 'Sx4',
       'Baleno', 'Alto K10', 'Swift Dzire', 'Alto 800', 'Santro', 'Ritz',
       'Etios', 'Zen', 'Jazz', 'Corolla Altis', 'Elantra', 'Estilo',
       'Brio', 'Ertiga', 'Celerio', 'Camry', 'Eeco', 'I20 Active',
       'Santa Fe', 'Verna Transform', 'Sonata', 'Getz Prime', 'Cr-V',
       'City Zx', 'Mobilio', 'Civic Hybrid', 'Corolla', 'S-Cross',
       'Wagon R Duo', 'Etios Cross', 'Omni', 'Etios Liva', 'Swift ',
       'A-Star', 'Innova Crysta', 'Esteem', 'Stingray', 'Platinum Etios',
       '800', 'Kizashi', 'Land Cruiser'], dtype=object)

In [24]:
'I20':1, 'Neo Fluidic Elantra':0, 'Santro Xing':2, 'Grand I10':3, 'Accent':4,'Creta':5, 'Elite I20':6, 'Verna':7, 'I10':8, 'Eon':9, 'Xcent':10, 'Getz':11,'City':12, 'Accord':13, 'Ciaz':14, 'Wagon R':15, 'Swift':16, 'Innova':17, 'Fortuner':18,'Alto':19, 'Wagon R 1.0':20, 'Vitara Brezza':21, 'Amaze':22, 'Civic':23, 'Sx4':24,'Baleno':25, 'Alto K10':26, 'Swift Dzire':27, 'Alto 800':28, 'Santro':29, 'Ritz':30,'Etios':31, 'Zen':32, 'Jazz':33, 'Corolla Altis':34, 'Elantra':35, 'Estilo':36,'Brio':37, 'Ertiga':38, 'Celerio':39, 'Camry':40, 'Eeco':41, 'I20 Active':42,'Santa Fe':43, 'Verna Transform':44, 'Sonata':45, 'Getz Prime':46, 'Cr-V':47,'City Zx':48, 'Mobilio':49, 'Civic Hybrid':50, 'Corolla':51, 'S-Cross':52,'Wagon R Duo':53, 'Etios Cross':54, 'Omni':55, 'Etios Liva':56, 'Swift ':57,'A-Star':58, 'Innova Crysta':59, 'Esteem':60, 'Stingray':61, 'Platinum Etios':62,'800':63, 'Kizashi':64, 'Land Cruiser':65

SyntaxError: invalid syntax (<ipython-input-24-228d5df884d1>, line 1)

In [43]:
df['Model'] = df['Model'].map( {'I20':1, 'Neo Fluidic Elantra':0, 'Santro Xing':2, 'Grand I10':3, 'Accent':4,'Creta':5, 'Elite I20':6, 'Verna':7, 'I10':8, 'Eon':9, 'Xcent':10, 'Getz':11,'City':12, 'Accord':13, 'Ciaz':14, 'Wagon R':15, 'Swift':16, 'Innova':17, 'Fortuner':18,'Alto':19, 'Wagon R 1.0':20, 'Vitara Brezza':21, 'Amaze':22, 'Civic':23, 'Sx4':24,'Baleno':25, 'Alto K10':26, 'Swift Dzire':27, 'Alto 800':28, 'Santro':29, 'Ritz':30,'Etios':31, 'Zen':32, 'Jazz':33, 'Corolla Altis':34, 'Elantra':35, 'Estilo':36,'Brio':37, 'Ertiga':38, 'Celerio':39, 'Camry':40, 'Eeco':41, 'I20 Active':42,'Santa Fe':43, 'Verna Transform':44, 'Sonata':45, 'Getz Prime':46, 'Cr-V':47,'City Zx':48, 'Mobilio':49, 'Civic Hybrid':50, 'Corolla':51, 'S-Cross':52,'Wagon R Duo':53, 'Etios Cross':54, 'Omni':55, 'Etios Liva':56, 'Swift ':57,'A-Star':58, 'Innova Crysta':59, 'Esteem':60, 'Stingray':61, 'Platinum Etios':62,'800':63, 'Kizashi':64, 'Land Cruiser':65 } ).astype(int)

In [44]:
df['Model'].dtype

dtype('int64')

In [31]:
df['Transmission'].unique()

array(['Manual', 'Automatic', 'Automated Manual Transmission'],
      dtype=object)

In [32]:
df['Transmission']=df['Transmission'].map({'Manual':1, 'Automatic':0, 'Automated Manual Transmission':2}).astype(int)

In [33]:
df['Transmission'].dtype

dtype('int64')

In [49]:
len(df['Variant'].unique())

457

In [50]:
M=df['Variant'].unique()
N=df['Variant']

In [32]:
mam=df['Variant']

In [33]:
mam[165]

'VXI BS IV'

In [51]:
n=0
for i in range(457):
    for j in range(2107):
        if(M[i]==N[j]):
            N[j]=n
            
    n=n+1

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [36]:
df.shape

(369, 9)

In [37]:
for i in range(369):
    if(N[i]==129):
        print(i)

165


In [38]:
N[165]

129

In [53]:
df['Variant']=df['Variant'].astype(int)

In [54]:
df['Variant'].dtype

dtype('int64')

In [34]:
df.dtypes

ID               int64
Make             int64
Model            int64
Variant          int64
Type             int64
Fuel Type        int64
Transmission     int64
on road price    int64
dtype: object

In [57]:
df['Color'].unique()

array(['Beige', 'White', 'Silver', 'Golden', 'Red', 'Black', 'other',
       'Blue', 'Grey', 'Maroon', 'Nexa Blue', 'Urban Titanium', 'Brown',
       'Purple', 'Other', 'Bronze', 'Orange', 'Sleek Silver',
       'White Orchid Pearl', 'Cyan', 'Golden Brown', 'Superior White',
       'sky blue', 'silver', 'metallic', 'silver mica metallic', 'gold',
       'Green', 'Cobalt', 'Premium Urban Blue', 'black', 'Silver, Beige',
       'Pink', 'Violet', 'Polar White', 'Stardust', 'Red Passion',
       'Flame Orange'], dtype=object)

In [58]:
df["Color"] = df["Color"].replace( ['White','Polar White','White Orchid Pearl','Superior White'], 'White')
df["Color"] = df["Color"].replace(['Silver','Sleek Silver','Silver, Beige','silver','silver mica metallic'], 'Silver')                                

In [59]:
df["Color"] = df["Color"].replace(['Brown','Bronze','Stardust'], 'Brown')
df["Color"] = df["Color"].replace(['Green'], 'Green' ) 

In [60]:
df["Color"] = df["Color"].replace(['Red','Red Passion','Pink','Maroon','Flame Orange','Orange'], 'Red')
df["Color"] = df["Color"].replace(['Grey','metallic'], 'Grey') 

In [61]:
df["Color"] = df["Color"].replace(['Black','Urban Titanium','black'], 'Black')
df["Color"] = df["Color"].replace(['Blue','Nexa Blue','Violet','Purple','Premium Urban Blue', 'Cyan','sky blue','Cobalt'], 'Blue')                                  

In [62]:
df["Color"] = df["Color"].replace(['Golden','Golden Brown','gold'], 'Golden')
df["Color"] = df["Color"].replace(['Beige',], 'Beige')
#df["Color"] = df["Color"].replace(['Yellow'], 'Yellow')
df["Color"] = df["Color"].replace(['other','Other'], 'other')                                   

In [63]:
df['Color'].unique()

array(['Beige', 'White', 'Silver', 'Golden', 'Red', 'Black', 'other',
       'Blue', 'Grey', 'Brown', 'Green'], dtype=object)

In [64]:
df['Color'] = df['Color'].map( {'Silver': 1,'White' : 0,'Red':2,'Golden':3,'Grey':4,'Blue':5,'Brown':6,'Green':7,'Beige':8,'other':9,'Black':10} ).astype(int)

In [65]:
df['Color'].dtype

dtype('int64')

In [35]:
df.dtypes

ID               int64
Make             int64
Model            int64
Variant          int64
Type             int64
Fuel Type        int64
Transmission     int64
on road price    int64
dtype: object

In [36]:
df.drop(['ID'], axis=1, inplace=True)

In [37]:
df.to_csv('clustering_droom_new_annotated.csv')

In [38]:
df.columns

Index([u'Make', u'Model', u'Variant', u'Type', u'Fuel Type', u'Transmission',
       u'on road price'],
      dtype='object')

In [39]:
df.dtypes

Make             int64
Model            int64
Variant          int64
Type             int64
Fuel Type        int64
Transmission     int64
on road price    int64
dtype: object

In [40]:
df.head(2)

Make  Model  Variant  Type  Fuel Type  Transmission  on road price
0     1      0        0     1          1             1         537850
1     1      1        1     1          1             1         613863

In [68]:
df.drop(['Unnamed: 0','Dep','ID','droom_price_rev','outlier' ], axis=1, inplace=True)

In [41]:
df.head(2)

Make  Model  Variant  Type  Fuel Type  Transmission  on road price
0     1      0        0     1          1             1         537850
1     1      1        1     1          1             1         613863

In [42]:
df.dtypes

Make             int64
Model            int64
Variant          int64
Type             int64
Fuel Type        int64
Transmission     int64
on road price    int64
dtype: object

In [43]:
#f1=df['Age'].values
#f2=df['Color'].values
#f3=df['Dep'].values
f1=df['Fuel Type'].values
#f5=df['Heath_score'].values
#f6=df['Kms_run'].values
f2=df['Make'].values
f3=df['Model'].values
f4=df['Transmission'].values
f5=df['Type'].values
f6=df['Variant'].values
f7=df['on road price'].values

plt.scatter(f1,f2,f3,f4, f5,f6,f7,f8)
plt.show()

In [48]:
x=np.array([f1,f2,f4, f5,f6,f7])

In [49]:
x

array([[      1,       1,       1, ...,       1,       0,       0],
       [      1,       1,       1, ...,       2,       2,       3],
       [      1,       1,       1, ...,       2,       2,       1],
       [      1,       1,       1, ...,       1,       2,       2],
       [      0,       1,       0, ...,     471,     472,     473],
       [ 537850,  613863,  678359, ...,  611251,  997154, 1529402]])

In [50]:
x.shape

(6, 563)

In [51]:
x.shape
y=np.zeros((x.shape[1], x.shape[0]))

In [52]:
y

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
for i in range(0,563):
    y[i]=x[:,i].reshape(1,x.shape[0])

In [54]:
y

array([[1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
        0.000000e+00, 5.378500e+05],
       [1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
        1.000000e+00, 6.138630e+05],
       [1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
        0.000000e+00, 6.783590e+05],
       ...,
       [1.000000e+00, 2.000000e+00, 2.000000e+00, 1.000000e+00,
        4.710000e+02, 6.112510e+05],
       [0.000000e+00, 2.000000e+00, 2.000000e+00, 2.000000e+00,
        4.720000e+02, 9.971540e+05],
       [0.000000e+00, 3.000000e+00, 1.000000e+00, 2.000000e+00,
        4.730000e+02, 1.529402e+06]])

In [55]:
z=np.array(y)
len(z)

563

In [56]:
z

array([[1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
        0.000000e+00, 5.378500e+05],
       [1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
        1.000000e+00, 6.138630e+05],
       [1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
        0.000000e+00, 6.783590e+05],
       ...,
       [1.000000e+00, 2.000000e+00, 2.000000e+00, 1.000000e+00,
        4.710000e+02, 6.112510e+05],
       [0.000000e+00, 2.000000e+00, 2.000000e+00, 2.000000e+00,
        4.720000e+02, 9.971540e+05],
       [0.000000e+00, 3.000000e+00, 1.000000e+00, 2.000000e+00,
        4.730000e+02, 1.529402e+06]])

In [57]:
kmeans=KMeans(n_clusters=20)
kmeans.fit(z)
centroids=kmeans.cluster_centers_
labels=kmeans.labels_

In [60]:
labels

array([17,  0, 15, 18, 11, 15, 15, 11, 11,  6, 19, 11, 15,  0,  0, 14, 15,
       15,  0,  8, 15, 17, 15,  7, 15, 17, 15,  0, 15,  0, 17, 17, 11, 10,
       19, 12, 10,  6,  3, 14,  8, 14,  5, 14,  1,  1, 19,  0,  3, 17, 15,
        0,  7,  8, 10,  4, 10,  7,  3, 10,  5,  0, 17,  8,  5,  8, 15,  8,
        0, 17, 10,  5,  5,  0, 17,  5, 19,  0, 17, 11,  6,  5,  7, 10, 14,
       11, 19,  5,  0, 15, 15,  8, 15,  8, 15, 11,  5,  5,  5,  6, 12, 17,
       17, 11,  0, 17,  6,  0,  5, 19,  5,  5,  3, 11, 11,  0, 19, 19, 15,
       15, 17, 15, 11,  8, 15, 17, 19,  0, 19, 19, 17,  0, 11,  7, 17,  7,
       17, 10,  5, 15,  7, 13,  6,  3, 11,  0,  8,  3,  5, 11, 12, 10,  3,
        5,  8, 19, 14, 15, 14, 15,  8,  0,  8,  3, 10, 15,  3,  5, 19, 10,
        8, 17, 17,  9, 11, 14,  8,  0,  6, 14, 15, 16, 18,  5, 10, 15, 14,
       11, 18, 17, 11, 11, 19, 12, 10, 15, 10, 19,  4,  8, 17,  8, 10, 17,
       15,  0,  5,  5,  6, 17, 11, 17, 11,  8, 17,  8, 19,  5,  7,  3,  8,
       19,  5, 15, 19, 10

In [61]:
len(labels)

563

In [62]:
print centroids

[[8.00000000e-01 1.37777778e+00 1.04444444e+00 1.17777778e+00
  1.95222222e+02 6.17181311e+05]
 [1.00000000e+00 5.00000000e-01 5.00000000e-01 2.12500000e+00
  1.92375000e+02 2.46159862e+06]
 [1.00000000e+00 3.00000000e+00 0.00000000e+00 3.00000000e+00
  4.67000000e+02 1.09546640e+07]
 [4.82758621e-01 1.37931034e+00 8.27586207e-01 2.34482759e+00
  2.43241379e+02 1.33201493e+06]
 [2.50000000e-01 2.37500000e+00 6.25000000e-01 2.75000000e+00
  2.91375000e+02 3.14168862e+06]
 [8.08510638e-01 1.17021277e+00 8.51063830e-01 1.80851064e+00
  1.85340426e+02 8.31895043e+05]
 [5.18518519e-01 2.18518519e+00 7.03703704e-01 2.88888889e+00
  2.55555556e+02 1.71760922e+06]
 [1.03703704e+00 1.85185185e+00 1.00000000e+00 1.29629630e+00
  2.45259259e+02 3.52834296e+05]
 [5.80000000e-01 1.34000000e+00 7.60000000e-01 2.56000000e+00
  2.38300000e+02 1.17605056e+06]
 [0.00000000e+00 2.00000000e+00 0.00000000e+00 3.00000000e+00
  2.62000000e+02 3.92768250e+06]
 [4.51612903e-01 1.38709677e+00 7.09677419e-01 2.4

In [102]:
#print centroids
#print labels
#colors=["g.", "r.", "c.","y.", "b.", "m."]
for i in range(len(z)):
    #print ("coordinate:", z[i], "label", labels[i])
    plt.plot(z[i][0], z[i][1], z[i][2]], markersize=10)
plt.scatter(centroids[ :,0], centroids[:,1], marker='x', s=150, linewidths=5, zorder=10)

SyntaxError: invalid syntax (<ipython-input-102-10c9498264bb>, line 6)

In [66]:
df.head(2)

ID     Make Model        Variant       Type Fuel Type Transmission  \
0   1  Hyundai   I10     Sportz 1.2  Hatchback    Petrol       Manual   
1   2  Hyundai   I20  Magna (O) 1.2  Hatchback    Petrol       Manual   

   on road price  
0         537850  
1         613863

In [67]:
df['ID']=labels

In [68]:
df.head(2)

ID     Make Model        Variant       Type Fuel Type Transmission  \
0  17  Hyundai   I10     Sportz 1.2  Hatchback    Petrol       Manual   
1   0  Hyundai   I20  Magna (O) 1.2  Hatchback    Petrol       Manual   

   on road price  
0         537850  
1         613863

In [69]:
df=df.rename(columns={'ID':'labels'})

In [70]:
df.head(2)

labels     Make Model        Variant       Type Fuel Type Transmission  \
0      17  Hyundai   I10     Sportz 1.2  Hatchback    Petrol       Manual   
1       0  Hyundai   I20  Magna (O) 1.2  Hatchback    Petrol       Manual   

   on road price  
0         537850  
1         613863

In [96]:
df['Kms_run']=df['Kms_run'].replace(",","",regex=True)

In [97]:
df['Kms_run']=df['Kms_run'].astype(int)

In [98]:
df['Kms_run'].dtype

dtype('int64')

In [99]:
df.drop(['ID','droom_price_rev','outlier'], axis=1, inplace=True)

In [74]:
df.shape

(563, 8)

In [71]:
df.head(2)

labels     Make Model        Variant       Type Fuel Type Transmission  \
0      17  Hyundai   I10     Sportz 1.2  Hatchback    Petrol       Manual   
1       0  Hyundai   I20  Magna (O) 1.2  Hatchback    Petrol       Manual   

   on road price  
0         537850  
1         613863

In [72]:
df=df.rename(columns={'Fuel Type':'Fuel_type', 'on road price':'on_road_price'})

In [73]:
df.head(2)

labels     Make Model        Variant       Type Fuel_type Transmission  \
0      17  Hyundai   I10     Sportz 1.2  Hatchback    Petrol       Manual   
1       0  Hyundai   I20  Magna (O) 1.2  Hatchback    Petrol       Manual   

   on_road_price  
0         537850  
1         613863

In [132]:
labels=[]
Make=[]
Model=[]
Variant=[]
Type=[]
Fuel_type=[]
Transmission=[]
on_road_price=[]
for i in range(0,563):
    if df['labels'][i]==19:
        labels.append(df['labels'][i])
        Fuel_type.append(df['Fuel_type'][i])
        Make.append(df['Make'][i])
        Model.append(df['Model'][i])
        Transmission.append(df['Transmission'][i])
        Type.append(df['Type'][i])
        Variant.append(df['Variant'][i])
        on_road_price.append(df['on_road_price'][i])
        
        
data={'labels':labels,'Fuel_type':Fuel_type ,'Make':Make,'Model':Model,'Transmission':Transmission,'Type':Type, 'Variant':Variant, 'on_road_price':on_road_price }
dfe=pd.DataFrame(data=data)
dfe.head(2)


Fuel_type     Make      Model Transmission       Type            Variant  \
0    Diesel  Hyundai  Elite I20       Manual  Hatchback  Asta 1.4 CRDI (O)   
1    Petrol    Honda       City       Manual      Sedan           1.5 S MT   

   labels  on_road_price  
0      19         972640  
1      19         944779

In [133]:
dfe.shape

(48, 8)

In [134]:
dfe.to_csv('droom_for_new_labels19.csv')

In [14]:
x=np.matrix(zip(f1,f2,f3))
kmeans = KMeans(n_clusters=2).fit(x)

In [15]:
kmeans.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [ ]:
a