In [56]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [57]:
df=pd.read_csv('/home/shivam/Downloads/Droom model filtered.xlsx - Sheet1.csv')

In [58]:
df.head(2)

ID     Make Model     Variant       Type     Fuel Type  Age Transmission  \
0   1  Hyundai   I10  Sportz 1.2  Hatchback        Petrol    3       Manual   
1   8  Hyundai   I10       Magna  Hatchback  Petrol + CNG   10       Manual   

   Color     Kms  No of Owner  Droom Price  Heath score  price score  \
0  White  12,000            1       380000          8.5          8.8   
1    Red  55,000            2       185000          5.0          7.5   

   on road price  Droom Price rev %  Droom Price rev   Dep  
0         537850               11.0           338352  37.1  
1         462988               12.0           162800  64.8

In [59]:
df.shape

(1596, 18)

In [61]:
df.drop(['Droom Price','Droom Price rev %','Droom Price rev','ID'],axis=1,inplace=True)

#df['Variant'].unique()

In [63]:
df.head(2)

Make Model     Variant       Type     Fuel Type  Age Transmission  \
0  Hyundai   I10  Sportz 1.2  Hatchback        Petrol    3       Manual   
1  Hyundai   I10       Magna  Hatchback  Petrol + CNG   10       Manual   

   Color     Kms  No of Owner  Heath score  price score  on road price   Dep  
0  White  12,000            1          8.5          8.8         537850  37.1  
1    Red  55,000            2          5.0          7.5         462988  64.8

In [64]:
df.shape

(1596, 14)

In [65]:
len(df['Variant'].unique())

34

In [66]:
M=df['Variant'].unique()
N=df['Variant']

In [67]:
n=0
for i in range(34):
    for j in range(1596):
        if(M[i]==N[j]):
            N[j]=n
            
    n=n+1

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [68]:
df['Variant']=df['Variant'].astype(int)

In [70]:
df['Variant'].dtype

dtype('int64')

In [71]:
len(df['Model'].unique())

21

In [72]:
O=df['Model'].unique()
P=df['Model']

In [73]:
m=0
for i in range(21):
    for j in range(1596):
        if(O[i]==P[j]):
            P[j]=m
            
    m=m+1

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [74]:
df['Model']=df['Model'].astype(int)

In [76]:
df['Model'].dtype

dtype('int64')

In [77]:
df.head(2)

Make  Model  Variant       Type     Fuel Type  Age Transmission  Color  \
0  Hyundai      0        0  Hatchback        Petrol    3       Manual  White   
1  Hyundai      0        1  Hatchback  Petrol + CNG   10       Manual    Red   

      Kms  No of Owner  Heath score  price score  on road price   Dep  
0  12,000            1          8.5          8.8         537850  37.1  
1  55,000            2          5.0          7.5         462988  64.8

In [78]:
df.dtypes

Make              object
Model              int64
Variant            int64
Type              object
Fuel Type         object
Age                int64
Transmission      object
Color             object
Kms               object
No of Owner        int64
Heath score      float64
price score      float64
on road price      int64
Dep              float64
dtype: object

In [79]:
df['Color'].unique()

array(['White', 'Red', 'Grey', 'Silver', 'Blue', 'Golden', 'other',
       'Beige', 'bold beige metallic', 'Black', 'Brown', 'gold', 'Maroon',
       'Bronze', 'Other', 'Purple', 'Yellow', 'silver',
       'champagne and metallic', 'Chocolate Gold', 'Black, Maroon',
       'Orange', 'Pink', 'Green'], dtype=object)

In [80]:
df["Color"] = df["Color"].replace( ['White',], 'White')
df["Color"] = df["Color"].replace(['Silver','silver'], 'Silver')                                

In [81]:
df["Color"] = df["Color"].replace(['Brown','Bronze'], 'Brown')
df["Color"] = df["Color"].replace(['Green'], 'Green' )                                 

In [82]:
df["Color"] = df["Color"].replace(['Red','Orange', 'Pink','Maroon'], 'Red')
df["Color"] = df["Color"].replace(['Grey','champagne and metallic'], 'Grey')                                 

In [83]:
df["Color"] = df["Color"].replace(['Black','Black, Maroon'], 'Black')
df["Color"] = df["Color"].replace(['Blue','Purple'], 'Blue')                                  

In [84]:
df["Color"] = df["Color"].replace(['Golden','gold','Chocolate Gold'], 'Golden')
df["Color"] = df["Color"].replace(['Beige','bold beige metallic'], 'Beige')
df["Color"] = df["Color"].replace(['Yellow'], 'Yellow')
df["Color"] = df["Color"].replace(['other','Other'], 'other')                                   

In [85]:
df['Color'].unique()

array(['White', 'Red', 'Grey', 'Silver', 'Blue', 'Golden', 'other',
       'Beige', 'Black', 'Brown', 'Yellow', 'Green'], dtype=object)

In [86]:
df['Color'] = df['Color'].map( {'Silver': 1,'White' : 0,'Red':2,'Golden':3,'Grey':4,'Blue':5,'Brown':6,'Green':7,'Beige':8,'other':9,'Black':10,'Yellow':11   } ).astype(int)

In [87]:
df['Color'].dtype

dtype('int64')

In [89]:
df['Fuel Type'].unique()

array(['Petrol', 'Petrol + CNG', 'Diesel', 'diesel', 'cng', 'CNG',
       'Petrol + LPG'], dtype=object)

In [91]:
df['Fuel Type'] = df['Fuel Type'].replace(['Petrol','Petrol + CNG','Petrol + LPG' ], 'Petrol')
df['Fuel Type'] = df['Fuel Type'].replace([ 'Diesel', 'diesel'], 'Diesel')
df['Fuel Type'] = df['Fuel Type'].replace(['LPG'], 'LPG')
df['Fuel Type'] = df['Fuel Type'].replace(['cng', 'CNG' ], 'CNG')

In [92]:
df['Fuel Type'] = df['Fuel Type'].map( {'Petrol': 1, 'Diesel': 0, 'CNG':2 ,'LPG':3} ).astype(int)

In [93]:
df['Fuel Type'].dtype

dtype('int64')

In [95]:
df['Kms'][1]

'55,000'

In [97]:
for i in range(1596):
    df['Kms'][i]=df['Kms'][i].replace(',','') 

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [98]:
df['Kms'][275]

'38500'

In [99]:
for i in range(1596):
    df['Kms'][i]=float(df['Kms'][i])

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [100]:
df['Kms'] = df['Kms'].astype(float)

In [102]:
df['Kms'].dtype

dtype('float64')

In [103]:
df['Make'].unique()

array(['Hyundai', 'Honda', 'Maruti Suzuki', 'Toyota'], dtype=object)

In [104]:
df['Make'] = df['Make'].map( {'Hyundai': 1,'Honda' : 0, 'Maruti Suzuki':2,'Toyota':3 } ).astype(int)

In [105]:
df['Make'].dtype

dtype('int64')

df['Model'].unique()

'I10':1, 'I20':0, 'Verna':2, 'City':3, 'Civic':4, 'City Zx':5, 'Accord':6,'Brio':7, 'Sx4':8, 'Alto':9, 'Corolla Altis':10, 'Innova':11, 'Swift Dzire':12,'Swift':13, 'Wagon R 1.0':14, 'Wagon R':15, 'Santro Xing':16, 'Eeco':17, 'Ritz':18,'Estilo':19, 'Ertiga':20

df['Model']=df['Model'].map({'I10':1, 'I20':0, 'Verna':2, 'City':3, 'Civic':4, 'City Zx':5, 'Accord':6,'Brio':7, 'Sx4':8, 'Alto':9, 'Corolla Altis':10, 'Innova':11, 'Swift Dzire':12,'Swift':13, 'Wagon R 1.0':14, 'Wagon R':15, 'Santro Xing':16, 'Eeco':17, 'Ritz':18,'Estilo':19, 'Ertiga':20}).astype(int)

In [38]:
df['Model'].dtype

dtype('int64')

In [106]:
df['Type'].unique()

array(['Hatchback', 'Sedan', 'MUV', 'Van'], dtype=object)

In [107]:
df['Type']=df['Type'].map({'Hatchback':1, 'Sedan':0, 'MUV':2, 'Van':3, 'SUV':4, 'Crossover':5}).astype(int)

In [108]:
df['Type'].dtype

dtype('int64')

In [109]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [110]:
df['Transmission']=df['Transmission'].map({'Manual':1, 'Automatic':0,'Automated Manual Transmission':2 }).astype(int)

In [111]:
df['Transmission'].dtype

dtype('int64')

In [112]:
df.dtypes

Make               int64
Model              int64
Variant            int64
Type               int64
Fuel Type          int64
Age                int64
Transmission       int64
Color              int64
Kms              float64
No of Owner        int64
Heath score      float64
price score      float64
on road price      int64
Dep              float64
dtype: object

In [113]:
df.head(2)

Make  Model  Variant  Type  Fuel Type  Age  Transmission  Color      Kms  \
0     1      0        0     1          1    3             1      0  12000.0   
1     1      0        1     1          1   10             1      2  55000.0   

   No of Owner  Heath score  price score  on road price   Dep  
0            1          8.5          8.8         537850  37.1  
1            2          5.0          7.5         462988  64.8

In [114]:
df.to_csv('droom_new_annotated.csv')

In [15]:
Silver=1
White=0
Red=2
Golden=3
Grey=4
Blue=5
Brown=6
Green=7
Beige=8
other=9
Black=10
Yellow=11

In [16]:
Petrol=1
Diesel=0
CNG=2
LPG=3

In [17]:
Hyundai=1
Honda=0
Maruti_Suzuki=2
Toyota=3

In [18]:
Accord=6
Alto=9
Brio=7
I10=1
I20=0
City=3
Civic=4
City_Zx=5
Corolla_Altis=10
Eeco=17
Estilo=19
Ertiga=20
Innova=11
Ritz=18
Swift_Dzire=12
Swift=13
Santro_Xing=16
Sx4=8
Verna=2
Wagon_R_10=14
Wagon_R=15

In [19]:
Manual=1
Automatic=0

In [20]:
Hatchback=1
Sedan=0
MUV=2
Van=3
SUV=4

In [21]:
Sportz_12=0
Magna=1
Era=2
Magna_12=3
Fluidic_16_CRDi_SX=4
Asta_12=5
Sportz_12_AT=6
_15_S_MT=7
_18S_MT=8
_18V_AT=9
_15_V_AT=10
_15_V_MT=11
GXi=12
_24_AT=13
S_MT=14
VXi=15
LXI=16
_18_G=17
_25G=18
_25_V_7_STR=19
VDi=20
LXi_CNG=21
ZXi=22
EXi=23
LDi=24
Vxi13=25
VXI=26
GLS=27
LxiCng=28
_7_STR=29
_18V_MT=30
Vdi_BS_IV=31
LXi=32
ZDi=33

In [31]:
df['Age'][0]=2
df['Color'][0]=Red
df['Heath_score'][0]=8.4
df['Kms_run'][0]=4500
df['Make'][0]=Maruti_Suzuki
df['Model'][0]=Alto
df['Variant'][0]=VXI
df['Transmission'][0]=Manual
df['Fuel_type'][0]=Petrol
df['Type'][0]=Hatchback
#df['droom_price_rev'][0]=250000
df['on_road_price'][0]=360885
df['owners'][0]=1
df['price_score'][0]=8.1

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python2.7/dist-p

In [38]:
df.head(2)

Age Color   Dep     Fuel_type  Heath_score Kms_run     Make Model  \
0    2     2  37.1             1          8.4    4500        2     9   
1   10   Red  64.8  Petrol + CNG          5.0  55,000  Hyundai   I10   

  Transmission       Type Variant  droom_price_rev  on_road_price  owners  \
0            1          1      26           242708         360885       1   
1       Manual  Hatchback   Magna           162800         462988       2   

   price_score  
0          8.1  
1          7.5

In [24]:
df.drop(['Unnamed: 0','ID', 'outlier'], axis=1, inplace=True)

In [25]:
df.head(2)

Age Color   Dep     Fuel_type  Heath_score Kms_run     Make Model  \
0    2     2  37.1             1          8.4    4500        2     9   
1   10   Red  64.8  Petrol + CNG          5.0  55,000  Hyundai   I10   

  Transmission       Type Variant  droom_price_rev  on_road_price  owners  \
0            1          1      26           250000         340964       1   
1       Manual  Hatchback   Magna           162800         462988       2   

   price_score  
0          8.1  
1          7.5

In [39]:
x_pred = df.head(1).drop('Dep', axis=1)

In [40]:
predicted_value = model2.predict(x_pred)

In [41]:
predicted_value

array([32.7541332])

In [42]:
df['droom_price_rev'][0]=(360885-(360885/100)*predicted_value)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [43]:
df['droom_price_rev'][0]

242708

In [54]:
df.to_csv('droom_unique_annotated_rev.csv')

In [3]:
df1=pd.read_csv('droom_unique_annotated_rev.csv')

In [115]:
df.head(2)

Make  Model  Variant  Type  Fuel Type  Age  Transmission  Color      Kms  \
0     1      0        0     1          1    3             1      0  12000.0   
1     1      0        1     1          1   10             1      2  55000.0   

   No of Owner  Heath score  price score  on road price   Dep  
0            1          8.5          8.8         537850  37.1  
1            2          5.0          7.5         462988  64.8

In [5]:
df1.drop(['Unnamed: 0'], axis=1, inplace=True)

In [116]:
df.shape

(1596, 14)

In [117]:
x = df.drop('Dep', axis=1)
y = df['Dep']

In [118]:
len(x.columns)

13

In [119]:
X_train, X_test, Y_train, y_test = train_test_split(x, y, test_size=0.10, random_state=32)

In [120]:
from sklearn.ensemble import RandomForestRegressor
model1 = RandomForestRegressor(n_estimators=500, max_features="sqrt")
model1 = model1.fit(X_train, Y_train )
y_pred1 = model1.predict(X_test)

In [121]:
scores = cross_val_score(model1,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred1))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()

()
Scores:
[0.77792404 0.75758783 0.78907067 0.80380774 0.78904921]
Mean absolute error:
3.82937841667
Mean percent error: 
0.06862377880321995
()


In [122]:
from sklearn.ensemble import GradientBoostingRegressor
model2= GradientBoostingRegressor()
model2=model2.fit(X_train, Y_train)
y_pred2 = model2.predict(X_test)

In [123]:
scores = cross_val_score(model2,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred2))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()

()
Scores:
[0.79411212 0.81406248 0.88129459 0.87144857 0.84503463]
Mean absolute error:
3.10025327151
Mean percent error: 
0.05555760533147586
()


In [83]:
df['model'] = df['model'].map( {'Alto 800': 1,'Eeco' : 0,'Alto K10':2,'Ciaz':3, 'Wagon R 1.0':4,'Baleno':5,'Swift':6,'Celerio':7,'Ertiga':8,'Ignis':9,'Swift Dzire':10,'S-Cross':11,'Dzire':12,'Vitara Brezza':13,'Alto':14,'Stingray':15, 'Estilo':16, 'City':17,'Ritz':18, 'A-Star':19, 'Gypsy':20, 'Wagon R':21, 'Omni':22, 'i20':23,'Corolla Altis':24, 'Verna':25, 'Getz':26, 'SX4':27, 'i10':28, 'Grand i10':29,'Elantra':30, 'Xcent':31, 'Swift DZire':32, 'Eon':33, 'Esteem':34, 'Etios':35,'City ZX':36, 'Jazz':37, 'Etios Liva':38, 'Accord':39, 'Elite i20':40, 'Creta':41,'Fortuner':42, 'i20 Active':43, 'Accent':44, 'Santro Xing':45, 'Santa Fe':46,'Innova Crysta':47, 'Amaze':48, 'Brio':49, 'BR-V':50, 'CR-V':51, 'Mobilio':52,'Civic':53, 'Etios Cross':54, 'Corolla':55, 'Innova':56, 'Kizashi':57,'Land Cruiser Prado':58, 'Prius':59, 'Sonata':60, 'Fluidic Verna 4S':61,'Verna Transform':62, 'WR-V':63 } ).astype(int)

In [85]:
df['fuel_type'] = df['fuel_type'].map( {'Petrol': 1,'CNG' : 0,'Diesel':2,'LPG':3  } ).astype(int)

In [86]:
df['make'] = df['make'].map( {'Maruti Suzuki': 1,'Toyota' : 0,'Hyundai':2,'Honda':3  } ).astype(int)

In [87]:
df['transmission'] = df['transmission'].map( {'Manual': 1,'Automatic' : 0} ).astype(int)

In [88]:
df.head(2)

Depriciation  age  color  fuel_type  kms_run  make  model  owners  \
0     29.300927    1      1          1      836     1      1       1   
1     22.897497    2      0          1     1900     1      0       1   

   transmission  
0             1  
1             1

In [7]:
df.shape

(5092, 10)

In [8]:
df.dtypes

Age               int64
Depreciation    float64
MMV               int64
color             int64
fuel_type         int64
kms_run           int64
make              int64
model             int64
owners            int64
transmission      int64
dtype: object

In [14]:
x = df.drop('Depreciation', axis=1)
y = df['Depreciation']

In [15]:
X_train, X_test, Y_train, y_test = train_test_split(x, y, test_size=0.10, random_state=32)

In [16]:
from sklearn.ensemble import RandomForestRegressor
model1 = RandomForestRegressor(n_estimators=500, max_features="sqrt")
model1 = model1.fit(X_train, Y_train )
y_pred1 = model1.predict(X_test)

In [17]:
scores = cross_val_score(model1,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred1))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()


()
Scores:
[0.87696029 0.85444183 0.86177777 0.87523256 0.85763935]
Mean absolute error:
4.18271570418
Mean percent error: 
0.08461426018825097
()


In [130]:
er=y_test-y_pred1

In [137]:
abs(er)

163      2.087003
1628     2.680849
937      4.668617
2249     4.440791
2100     0.511570
1877     4.319916
1593     3.164188
2362     2.823924
2141     0.965543
1398    11.915772
2817     4.217357
1378     6.631988
18      10.151859
290      1.389219
2523     3.162541
2345     1.805370
1507     6.263476
98       9.712680
238      3.054156
965      3.739579
2677     2.554175
317      4.078702
450      5.214388
2340     1.106221
1736     0.528760
1145     0.466338
1647     5.486571
2357     2.482734
2040     2.493021
1494     2.747175
          ...    
1832     0.058978
1347     5.183503
1843     3.113629
1696     0.009326
2608     1.500631
295     16.484524
726      4.042978
1170     0.357611
422      3.647112
124      7.764996
278      3.201963
763      0.252416
765      5.789492
2480     0.010726
348      1.454426
2210     1.001448
1814     6.416026
2189     0.023810
1883     2.967858
1849     1.165389
2846     5.973822
2230     5.072406
1452    18.473055
1853     2.497778
507      2

In [18]:
from sklearn.ensemble import GradientBoostingRegressor
model2= GradientBoostingRegressor()
model2=model2.fit(X_train, Y_train)
y_pred2 = model2.predict(X_test)

In [19]:
scores = cross_val_score(model2,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred2))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()

()
Scores:
[0.88390409 0.8194759  0.87460129 0.88071481 0.8929611 ]
Mean absolute error:
4.45563848636
Mean percent error: 
0.09013535244887697
()


In [70]:
from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor(random_state=0)
model3=model3.fit(X_train, Y_train)
y_pred3 = model3.predict(X_test)

In [71]:
scores = cross_val_score(model3,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred3))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()

()
Scores:
[0.58063218 0.64073011 0.42330111 0.63895415 0.67572013]
Mean absolute error:
6.06394736842
Mean percent error: 
0.11126508932882667
()


In [72]:
from sklearn import neural_network
model4=neural_network.MLPRegressor()
model4=model4.fit(X_train, Y_train)
y_pred4 = model4.predict(X_test)

In [73]:
scores = cross_val_score(model4,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred4))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()

()
Scores:
[-2374735.73259283 -3236433.92364608 -4480647.11910092   -61115.35374972
 -1664150.21391967]
Mean absolute error:
82.8998170987
Mean percent error: 
1.5210975614433475
()


In [125]:
from sklearn import neural_network
model5=neural_network.MLPRegressor(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5,2), random_state=1)
model5=model5.fit(X_train, Y_train)
y_pred5 = model5.predict(X_test)

In [108]:
scores = cross_val_score(model5,X_test,y_test, cv = 5)
print()

print("Scores:")
print(scores)
print("Mean absolute error:")
mean_error = sum(abs(y_test-y_pred5))/len(y_test)
print(mean_error);
print("Mean percent error: ")
print(mean_error/np.mean(y_test))
print()

()
Scores:
[-0.00232004 -0.01495436 -0.05671014 -0.0186222  -0.00200983]
Mean absolute error:
13.2308128152
Mean percent error: 
0.2503495316772608
()
